### ISSUE TITLE
Keppel hangs on "Please place finger on scanner" but the scanner light never turned on

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#22]
An attempt to scan the wrong finger during the `MATCH` flow caused an exception, and the scanner never lit up to accept a scan (using an embedded BioMini scanner).

```
2024-07-15 10:40:51.367   736-1763  InputManager-JNI        system_server                        W  Input channel object '35a01f8 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity (client)' was disposed without first being removed with the input manager!
2024-07-15 10:40:52.023   736-1763  ActivityTaskManager     system_server                        I  START u0 {act=uk.ac.lshtm.keppel.android.MATCH cmp=uk.ac.lshtm.keppel.android/.scanning.ScanActivity (has extras)} from uid 10139
2024-07-15 10:40:52.076  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Key value expected String but value was a java.lang.Double.  The default value <null> was returned.
2024-07-15 10:40:52.076  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8917)
                                                                                                    	at uk.ac.lshtm.keppel.android.OdkExternal.parseIntent(OdkExternal.kt:43)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.IntentParser.parse(IntentParser.kt:10)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScanActivity.onCreate(ScanActivity.kt:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8356)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8335)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-07-15 10:40:52.076  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Key value expected String but value was a java.lang.Double.  The default value <null> was returned.
2024-07-15 10:40:52.076  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8917)
                                                                                                    	at uk.ac.lshtm.keppel.android.OdkExternal.parseIntent(OdkExternal.kt:54)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.IntentParser.parse(IntentParser.kt:10)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScanActivity.onCreate(ScanActivity.kt:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8356)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8335)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by seadowg** [comment]
Closing this as we've not been able to reproduce.
