### ISSUE TITLE
`NullPointerException` in `ScanActivity`

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#25]
Also not sure how to reproduce this, but here's another exception we saw.

```
2024-07-15 10:26:15.441  4350-4350  AndroidRuntime          uk.ac.lshtm.keppel.android           E  FATAL EXCEPTION: main
                                                                                                    Process: uk.ac.lshtm.keppel.android, PID: 4350
                                                                                                    java.lang.RuntimeException: Unable to pause activity {uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.nio.ByteBuffer.isDirect()' on a null object reference
                                                                                                    	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5071)
                                                                                                    	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5022)
                                                                                                    	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4974)
                                                                                                    	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.nio.ByteBuffer.isDirect()' on a null object reference
                                                                                                    	at android.hardware.usb.UsbRequest.dequeue(UsbRequest.java:380)
                                                                                                    	at android.hardware.usb.UsbDeviceConnection.requestWait(UsbDeviceConnection.java:366)
                                                                                                    	at e.c.c(Unknown Source:21)
                                                                                                    	at e.c.a(Unknown Source:92)
                                                                                                    	at e.c.b(Unknown Source:13)
                                                                                                    	at com.suprema.hid.BioMiniHidBase.m(Unknown Source:76)
                                                                                                    	at com.suprema.hid.BioMiniHidBase.abortCapturing(Unknown Source:19)
                                                                                                    	at uk.ac.lshtm.keppel.biomini.BioMiniScanner.stopCapture(BioMiniScanner.kt:318)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScannerViewModel.stopCapture(ScannerViewModel.kt:66)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScanActivity.onPause(ScanActivity.kt:108)
                                                                                                    	at android.app.Activity.performPause(Activity.java:8532)
                                                                                                    	at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1618)
                                                                                                    	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5061)
                                                                                                    	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5022) 
                                                                                                    	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4974) 
                                                                                                    	at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:48) 
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 

```

**Comment by tobiasmcnulty** [comment]
Duplicate of #28
