### ISSUE TITLE
`java.lang.Double cannot be cast to java.lang.String` launching `MATCH` function

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#26]
Launching `MATCH` causes a `java.lang.Double cannot be cast to java.lang.String` to be logged, but the match function still works fine.

```
2024-07-15 10:52:42.638  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  run: abortCapturing : 0
2024-07-15 10:52:42.964  6864-6886  OpenGLRenderer          uk.ac.lshtm.keppel.android           D  endAllActiveAnimators on 0xb400007bbc1e5590 (RippleDrawable) with handle 0xb400007acbffcd10
2024-07-15 10:52:42.976  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  ACTION_USB_DEVICE_DETACHED
2024-07-15 10:52:42.977   736-796   CoreBackPreview         system_server                        D  Window{1dc809 u0 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity}: Setting back callback null
2024-07-15 10:52:42.978   736-796   InputManager-JNI        system_server                        W  Input channel object '1dc809 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity (client)' was disposed without first being removed with the input manager!
2024-07-15 10:52:44.422   736-1758  ActivityTaskManager     system_server                        I  START u0 {act=uk.ac.lshtm.keppel.android.MATCH cmp=uk.ac.lshtm.keppel.android/.scanning.ScanActivity (has extras)} from uid 10139
2024-07-15 10:52:44.481  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Key value expected String but value was a java.lang.Double.  The default value <null> was returned.
2024-07-15 10:52:44.481  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8917)
                                                                                                    	at uk.ac.lshtm.keppel.android.OdkExternal.parseIntent(OdkExternal.kt:43)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.IntentParser.parse(IntentParser.kt:10)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScanActivity.onCreate(ScanActivity.kt:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8356)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8335)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-07-15 10:52:44.481  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Key value expected String but value was a java.lang.Double.  The default value <null> was returned.
2024-07-15 10:52:44.481  6864-6864  Bundle                  uk.ac.lshtm.keppel.android           W  Attempt to cast generated internal exception:
                                                                                                    java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
                                                                                                    	at android.os.BaseBundle.getString(BaseBundle.java:1377)
                                                                                                    	at android.content.Intent.getStringExtra(Intent.java:8917)
                                                                                                    	at uk.ac.lshtm.keppel.android.OdkExternal.parseIntent(OdkExternal.kt:54)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.IntentParser.parse(IntentParser.kt:10)
                                                                                                    	at uk.ac.lshtm.keppel.android.scanning.ScanActivity.onCreate(ScanActivity.kt:38)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8356)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8335)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7884)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2024-07-15 10:52:44.482  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  Device name: BioRugged BW10RS
2024-07-15 10:52:44.482  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  start initUsbListener!
2024-07-15 10:52:44.484  6864-6864  TAG                     uk.ac.lshtm.keppel.android           D  start!
2024-07-15 10:52:44.484  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  device id3034
2024-07-15 10:52:44.484  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  This device is not suprema device!  : 3034
2024-07-15 10:52:44.484  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  device id5841
2024-07-15 10:52:44.484  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  found suprema usb device
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  device id1155
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  This device is not suprema device!  : 1155
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  device id9969
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  This device is not suprema device!  : 9969
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  device id11388
2024-07-15 10:52:44.485  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  This device is not suprema device!  : 11388
2024-07-15 10:52:44.491   736-1758  CoreBackPreview         system_server                        D  Window{579bd7e u0 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@4849b2c, mPriority=0}
2024-07-15 10:52:44.491  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  got REQUEST_USB_PERMISSION
2024-07-15 10:52:44.509  6864-6886  OpenGLRenderer          uk.ac.lshtm.keppel.android           E  Unable to match the desired swap behavior.
2024-07-15 10:52:44.514  6864-6886  Parcel                  uk.ac.lshtm.keppel.android           W  Expecting binder but got null!
2024-07-15 10:52:44.514  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  ACTION_USB_PERMISSION
2024-07-15 10:52:44.514  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  /dev/bus/usb/006/018 is acquire the usb permission. activate this device.
2024-07-15 10:52:44.518  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  got ACTIVATE_USB_DEVICE
2024-07-15 10:52:44.519   736-754   ziparchive              system_server                        W  Unable to open '/data/app/~~ydl-7M7861MmQl2HbE38iA==/uk.ac.lshtm.keppel.android-Hxt312c9lMUOBf56hwpkCA==/base.dm': No such file or directory
2024-07-15 10:52:44.520   736-754   ActivityTaskManager     system_server                        I  Displayed uk.ac.lshtm.keppel.android/.scanning.ScanActivity: +97ms
2024-07-15 10:52:44.520  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  new BioMiniFactory( ) : uk.ac.lshtm.keppel.biomini.BioMiniScanner$createBioMiniDevice$1@b311490
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.522  6864-6864  UsbRequestJNI           uk.ac.lshtm.keppel.android           D  init
2024-07-15 10:52:44.951  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  mCurrentDevice attached : d.b@62171af
2024-07-15 10:52:44.952  6864-10054 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START!
2024-07-15 10:52:44.960  1399-1399  GoogleInpu...hodService com...gle.android.inputmethod.latin  I  GoogleInputMethodService.onStartInput():1930 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=uk.ac.lshtm.keppel.android fieldId=-1 fieldName=null extras=null}, false)
2024-07-15 10:52:44.987   736-1758  WindowManager           system_server                        V  getPackagePerformanceMode -- ComponentInfo{uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity} -- uk.ac.lshtm.keppel.android -- mode=0
2024-07-15 10:52:47.803  6864-10156 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START! : CAPTURE_SINGLE
2024-07-15 10:52:47.803  6864-10156 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  TemplateData is not null!
2024-07-15 10:52:47.849  6864-10156 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  mFpQuality : 2
2024-07-15 10:52:47.903  6864-10054 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START!
2024-07-15 10:52:48.398   736-757   ActivityTaskManager     system_server                        W  Activity pause timeout for ActivityRecord{6d0c501 u0 uk.ac.lshtm.keppel.android/.scanning.ScanActivity} t43 f}}
2024-07-15 10:52:48.535  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  run: abortCapturing : 0
2024-07-15 10:52:48.735  6864-6864  KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  ACTION_USB_DEVICE_DETACHED
2024-07-15 10:52:48.737   736-1758  CoreBackPreview         system_server                        D  Window{579bd7e u0 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity}: Setting back callback null
2024-07-15 10:52:48.739   736-1758  InputManager-JNI        system_server                        W  Input channel object '579bd7e uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity (client)' was disposed without first being removed with the input manager!

```

**Comment by seadowg** [comment]
Closing this as we've not been able to reproduce.
