### ISSUE TITLE
"Keppel keeps stopping" and `NullPointerException` after scanning wrong fingerprint during `MATCH`

### ISSUE THREAD

**Issue by tobiasmcnulty** [LSHTM-ORK/ODK_Biometrics#28]
```
2024-07-15 11:00:45.024 10919-10959 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START! : CAPTURE_SINGLE
2024-07-15 11:00:45.062 10919-10959 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  mFpQuality : 3
2024-07-15 11:00:45.065 10919-10955 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START!
2024-07-15 11:00:47.536 10919-10969 ProfileInstaller        uk.ac.lshtm.keppel.android           D  Installing profile for uk.ac.lshtm.keppel.android
2024-07-15 11:00:47.551 10919-10963 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START! : CAPTURE_SINGLE
2024-07-15 11:00:47.551 10919-10963 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  TemplateData is not null!
2024-07-15 11:00:47.590 10919-10963 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  mFpQuality : 2
2024-07-15 11:00:47.641 10919-10955 System.err              uk.ac.lshtm.keppel.android           W  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2024-07-15 11:00:47.641 10919-10955 System.err              uk.ac.lshtm.keppel.android           W  SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-07-15 11:00:47.641 10919-10955 System.err              uk.ac.lshtm.keppel.android           W  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-07-15 11:00:47.872 10919-10955 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  START!
2024-07-15 11:00:47.884 10919-10971 AndroidRuntime          uk.ac.lshtm.keppel.android           E  FATAL EXCEPTION: Thread-7
                                                                                                    Process: uk.ac.lshtm.keppel.android, PID: 10919
                                                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.nio.ByteBuffer.isDirect()' on a null object reference
                                                                                                    	at android.hardware.usb.UsbRequest.dequeue(UsbRequest.java:380)
                                                                                                    	at android.hardware.usb.UsbDeviceConnection.requestWait(UsbDeviceConnection.java:366)
                                                                                                    	at e.c.c(Unknown Source:21)
                                                                                                    	at e.c.a(Unknown Source:92)
                                                                                                    	at e.c.b(Unknown Source:13)
                                                                                                    	at com.suprema.hid.BioMiniHidBase.b(Unknown Source:149)
                                                                                                    	at com.suprema.hid.BioMiniHidBase$c.run(Unknown Source:6)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-07-15 11:00:47.886 10919-10919 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  run: abortCapturing : 0
2024-07-15 11:00:47.906   736-755   ActivityManager         system_server                        I  Showing crash dialog for package uk.ac.lshtm.keppel.android u0
2024-07-15 11:00:47.951   736-755   CoreBackPreview         system_server                        D  Window{d2a5b00 u0 Application Error: uk.ac.lshtm.keppel.android}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.WindowOnBackInvokedDispatcher$OnBackInvokedCallbackWrapper@30229fb, mPriority=0}
2024-07-15 11:00:48.776 10919-10919 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  run: abortCapturing : 0
2024-07-15 11:00:48.786 10919-10919 KeppelBioMiniScanner    uk.ac.lshtm.keppel.android           D  ACTION_USB_DEVICE_DETACHED
2024-07-15 11:00:48.790   736-752   CoreBackPreview         system_server                        D  Window{dccf86 u0 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity}: Setting back callback null
2024-07-15 11:00:48.793   736-752   InputManager-JNI        system_server                        W  Input channel object 'dccf86 uk.ac.lshtm.keppel.android/uk.ac.lshtm.keppel.android.scanning.ScanActivity (client)' was disposed without first being removed with the input manager!
2024-07-15 11:00:48.810 10919-10919 Choreographer           uk.ac.lshtm.keppel.android           I  Skipped 32 frames!  The application may be doing too much work on its main thread.

```

**Comment by seadowg** [comment]
Closing this as we've not been able to reproduce.
