### ISSUE TITLE
Crashes with Android 14 and 15 devices using BioMini Slim 3

### ISSUE THREAD

**Issue by chrissyhroberts** [LSHTM-ORK/ODK_Biometrics#43]
Trying to use the 0.4.1 release on Android 14 or Android 15 devices leads to a form crash and return to ODK Collect main page. 

Using Android 13 seems to work fine. 

Tested on the following devices with two different generic USB to USB-C adapters 

Pixel 7a Android 15 = Crashes to main page of ODK Collect
Galaxy Tab S8 Android 14 = Crashes to main page of ODK Collect
Redmi Note 11  Android 13 = Working

**Comment by seadowg** [comment]
It looks like this is a problem in the BioMini scanner code:

```
java.lang.IllegalArgumentException: uk.ac.lshtm.keppel.android: Targeting U+ (version 34 and above) disallows creating or retrieving a PendingIntent with FLAG_MUTABLE, an implicit Intent within and without FLAG_NO_CREATE and FLAG_ALLOW_UNSAFE_IMPLICIT_INTENT for security reasons. To retrieve an already existing PendingIntent, use FLAG_NO_CREATE, however, to create a new PendingIntent with an implicit Intent use FLAG_IMMUTABLE.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3226)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3209)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3151)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithFeature(IActivityManager.java:7000)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:765)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:748)
                                                                                                    	at uk.ac.lshtm.keppel.biomini.BioMiniScanner$mHandler$1.handleMessage(BioMiniScanner.kt:101)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:107)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeatureAsApp(ActivityManagerService.java:5584)
                                                                                                    	at com.android.server.am.ActivityManagerService.getIntentSenderWithFeature(ActivityManagerService.java:5526)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3460)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2812)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1500)
```
